# Site settings

title: 世界大了，不准嬉戏；遥遥长路，错综跷崎
SEOTitle: 我有我心底故事 | Tomy-Lee Blog
header-img: img/home-bg.jpg
email: tomyleee@163.com
description: "描述"
keyword: "我有我心底故事，Tomy-Lee"
url: "https://tomy-lee.github.io"
baseurl: ""
...